spring:
  profiles:
    active: prod
server:
  port: 9090
  session:
    timeout: 60
---

spring:
  profiles: dev
  application:
      name: pl-prd
  datasource:
    url:  jdbc:mysql://39.108.103.128:3306/product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:  root
    password:  123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
swagger:
  show: true

---

spring:
  profiles: prod
  application:
      name: pl-prd
  datasource:
    url:  jdbc:mysql://39.98.186.132:3306/product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:  product
    password:  123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
swagger:
  show: true
