spring:
  profiles:
    active: dev
server:
  port: 9090
---

spring:
  profiles: dev
  application:
      name: pl-prd
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:  root
    password:  yangyang520
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
swagger:
  show: true
